import { Copy, Edit3, EyeOff, Globe2, MoreHorizontal, Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { deleteProject, getAllProjects, saveProject } from '../../lib/firestore';
import { removeFile } from '../../lib/storage';
import type { Project } from '../../types/portfolio';

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load() { setLoading(true); try { setProjects(await getAllProjects()); } finally { setLoading(false); } }
  useEffect(() => { load().catch(() => setMessage('Não foi possível carregar os projetos.')); }, []);
  async function update(project: Project, changes: Partial<Project>) { const { id, createdAt, updatedAt, ...input } = { ...project, ...changes }; await saveProject(input, id); await load(); }
  async function duplicate(project: Project) { const { id, createdAt, updatedAt, ...input } = project; await saveProject({ ...input, title: `${project.title} (cópia)`, published: false, featured: false, order: project.order + 1 }); await load(); }
  async function destroy(project: Project) { if (!window.confirm(`Excluir "${project.title}"? Essa ação não pode ser desfeita.`)) return; await deleteProject(project.id); await Promise.all([removeFile(project.videoPath), removeFile(project.thumbnailPath)]); await load(); }
  return <div className="admin-page"><div className="admin-page-heading"><div><p className="eyebrow">CONTEÚDO</p><h1>Projetos</h1><p className="admin-muted">Organize os trabalhos que aparecem no portfólio.</p></div><Link className="admin-primary compact" to="/admin/projetos/novo"><Plus size={16} /> NOVO PROJETO</Link></div>{message && <p className="form-message error">{message}</p>}<section className="admin-table-panel">{loading ? <p className="empty-state">Carregando projetos...</p> : projects.length === 0 ? <p className="empty-state">Nenhum projeto cadastrado.</p> : <div className="project-list">{projects.map((project) => <article className="project-row" key={project.id}><div className="project-row-media">{project.thumbnailUrl ? <img src={project.thumbnailUrl} alt="" /> : <div className="media-fallback"><MoreHorizontal size={18} /></div>}</div><div className="project-row-main"><div className="project-row-title"><h2>{project.title}</h2>{project.featured && <span className="status-pill featured">Destaque</span>}</div><p>{project.category} {project.year && `· ${project.year}`} {project.client && `· ${project.client}`}</p></div><label className="order-field">ORDEM<input type="number" min="0" defaultValue={project.order} onBlur={(event) => update(project, { order: Number(event.target.value) }).catch(() => setMessage('Não foi possível atualizar a ordem.'))} /></label><span className={project.published ? 'status-pill published' : 'status-pill draft'}>{project.published ? 'Publicado' : 'Rascunho'}</span><div className="project-actions"><Link to={`/admin/projetos/${project.id}`} aria-label={`Editar ${project.title}`}><Edit3 size={17} /></Link><button type="button" onClick={() => duplicate(project)} aria-label="Duplicar projeto"><Copy size={17} /></button><button type="button" onClick={() => update(project, { published: !project.published }).catch(() => setMessage('Não foi possível alterar o status.'))} aria-label={project.published ? 'Ocultar projeto' : 'Publicar projeto'}>{project.published ? <EyeOff size={17} /> : <Globe2 size={17} />}</button><button className="danger" type="button" onClick={() => destroy(project).catch(() => setMessage('Não foi possível excluir o projeto.'))} aria-label="Excluir projeto"><Trash2 size={17} /></button></div></article>)}</div>}</section></div>;
}
